#ifndef SWIFT_RUNTIME_CMAKECONFIG_H
#define SWIFT_RUNTIME_CMAKECONFIG_H

#define SWIFT_BNI_OS_BUILD 0
#define SWIFT_BNI_XCODE_BUILD 0

/* #undef SWIFT_VERSION_MAJOR */
/* #undef SWIFT_VERSION_MINOR */

#endif // SWIFT_RUNTIME_CMAKECONFIG_H
