# Functionality
set(SwiftStdlib_ENABLE_CRASH_REPORTER_CLIENT ON CACHE BOOL "")
set(SwiftStdlib_ENABLE_OBJC_INTEROP ON CACHE BOOL "")
set(SwiftStdlib_ENABLE_TYPE_PRINTING ON CACHE BOOL "")
set(SwiftStdlib_ENABLE_COMMANDLINE_SUPPORT ON CACHE BOOL "")
set(SwiftStdlib_ENABLE_LIBRARY_EVOLUTION ON CACHE BOOL "")
set(SwiftStdlib_ENABLE_VECTOR_TYPES ON CACHE BOOL "")
set(SwiftStdlib_ENABLE_EXTRA_SOURCES ON CACHE BOOL "")
set(SwiftStdlib_ENABLE_ASYNC_FP ON CACHE BOOL "")
set(SwiftStdlib_CONCURRENCY_BACKEND "dispatch" CACHE STRING "")

# Libraries
set(SwiftStdlib_ENABLE_DIFFERENTIATION OFF CACHE BOOL "") # TODO! ENABLE ME!
set(SwiftStdlib_ENABLE_CONCURRENCY ON CACHE BOOL "")
set(SwiftStdlib_ENABLE_DISTRIBUTED ON CACHE BOOL "")
set(SwiftStdlib_ENABLE_REFLECTION ON CACHE BOOL "")
set(SwiftStdlib_ENABLE_BACKTRACING OFF CACHE BOOL "") # TODO! ENABLE ME!
set(SwiftStdlib_ENABLE_STRINGPROCESSING ON CACHE BOOL "")

# Platform info
set(SwiftStdlib_PLATFORM_OVERLAY "Darwin" CACHE STRING "")
set(SwiftStdlib_BUILD_PLATFORM_OVERLAY FALSE CACHE BOOL "")
