set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(BUILD_SHARED_LIBS YES CACHE BOOL "")

set(CMAKE_OSX_DEPLOYMENT_TARGET 16 CACHE STRING "" FORCE)

set(CMAKE_C_COMPILER_TARGET "arm64-apple-ios${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET "arm64-apple-ios${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_Swift_COMPILER_TARGET "arm64-apple-ios${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/apple-common.cmake")
