set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(BUILD_SHARED_LIBS YES CACHE BOOL "")

set(CMAKE_OSX_DEPLOYMENT_TARGET 14 CACHE STRING "")

set(CMAKE_C_COMPILER_TARGET "x86_64-apple-macos${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET "x86_64-apple-macos${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_Swift_COMPILER_TARGET "x86_64-apple-macos${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")

# TODO: Hook up catalyst support

include("${CMAKE_CURRENT_LIST_DIR}/apple-common.cmake")
